# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connect(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Connect")
        MainWindow.resize(308, 143)
        MainWindow.setStyleSheet("QMainWindow{\n"
                                 "    background-color:  #FFE293;\n"
                                 "    border-radius:7px;\n"
                                 "    font: 57 8pt \\\"Poppins Medium\\\";\n"
                                 "    color: rgb(0, 0, 0)\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.nameTextEdit.setGeometry(QtCore.QRect(120, 30, 150, 31))
        self.nameTextEdit.setStyleSheet("QPlainTextEdit{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    border-radius:7px;\n"
                                        "}")
        self.nameTextEdit.setPlainText("")
        self.nameTextEdit.setObjectName("nameTextEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 90, 30))
        self.label_3.setStyleSheet("QLable{\n"
                                   "    font: 8 7pt \\\"Poppins Medium\\\";\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 90, 90, 30))
        self.pushButton.setStyleSheet("QpushButton{\n"
                                      "    background-color: #333;\n"
                                      "    border-radius:7px;\n"
                                      "    color: white;\\n\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                      "stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Connect", "Connect"))
        self.label_3.setText(_translate("Connect", "NAME"))
        self.pushButton.setText(_translate("Connect", "Connect"))
