'''
Mypy check

Use Mypy project (https://github.com/python/mypy) to perform static type
checking of your code. Play around a little bit with Mypy, go through results and reports
generated by running the mypy, perform refactoring based on the mentioned results.

'''
from typing import Any, Optional, Iterator, Protocol


def with_index(iterable: int, start: int = 0) -> Iterator[int]:
    for elem in iterable:
        yield start, elem
        start += 1


class Talking(Protocol):
    def talk(self) -> str:
        ...  #abstract

class Dog():
    def talk(self) -> str:
        return "woof!"

def animal_talk(animal: Talking):
    talk_animal = animal.talk()
    print(f'You hear a "{talk_animal}"')


class Person:
    firstname: str
    lastname: str
    age: int

    def __init__(self, firstname: str, lastname: str, age: int) -> None:
        self.firstname = firstname
        self.lastname = lastname
        self.age = age

    def rename(self, new: str) -> None:
        self.firstname = new

    def __repr__(self) -> str:
        return f"Hello, my name is {self.firstname} {self.lastname} and I’m {self.age} years old"


if __name__ == '__main__':
    seasons = ["Spring", "Summer", "Fall", "Winter"]
    seasons_list = list(with_index(seasons, start=1))
    print(seasons_list)

    animal_talk(Dog())

    person = Person("Carl", "Johnson", 26)
    person.rename("Jack")
    print(person.__repr__())
