# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Calculator")
        MainWindow.resize(248, 369)
        MainWindow.setStyleSheet("QMainWindow {\n"
"  background: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 246, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK JP")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"    color: white;\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(2, 61, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"      background: #a5a5a5;\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_module = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_module.setGeometry(QtCore.QRect(63, 61, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_module.setFont(font)
        self.pushButton_module.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"      background: #a5a5a5;\n"
"}")
        self.pushButton_module.setObjectName("pushButton_module")
        self.pushButton_percent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_percent.setGeometry(QtCore.QRect(124, 61, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"      background: #a5a5a5;\n"
"}")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.pushButton_divide = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(185, 61, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setStyleSheet("QPushButton {\n"
"   background: #f1a33c;\n"
"}")
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(63, 122, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(124, 122, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(2, 122, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multiply.setGeometry(QtCore.QRect(185, 122, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("QPushButton {\n"
"   background: #f1a33c;\n"
"}")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(63, 183, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(124, 183, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(2, 183, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_substract = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_substract.setGeometry(QtCore.QRect(185, 183, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_substract.setFont(font)
        self.pushButton_substract.setStyleSheet("QPushButton {\n"
"   background: #f1a33c;\n"
"}")
        self.pushButton_substract.setObjectName("pushButton_substract")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(63, 244, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(124, 244, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(2, 244, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(185, 244, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"   background: #f1a33c;\n"
"}")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_decimal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_decimal.setGeometry(QtCore.QRect(124, 305, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_decimal.setFont(font)
        self.pushButton_decimal.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_decimal.setObjectName("pushButton_decimal")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(2, 305, 122, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"    align-items: center;\n"
"    color: white;\n"
"    background: #333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_equals = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equals.setGeometry(QtCore.QRect(185, 305, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setStyleSheet("QPushButton {\n"
"   background: #f1a33c;\n"
"}")
        self.pushButton_equals.setObjectName("pushButton_equals")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Calculator", "Calculator"))
        self.label.setText(_translate("Calculator", "0"))
        self.pushButton_clear.setText(_translate("Calculator", "AC"))
        self.pushButton_module.setText(_translate("Calculator", "+/-"))
        self.pushButton_percent.setText(_translate("Calculator", "%"))
        self.pushButton_divide.setText(_translate("Calculator", "÷"))
        self.pushButton_8.setText(_translate("Calculator", "8"))
        self.pushButton_9.setText(_translate("Calculator", "9"))
        self.pushButton_7.setText(_translate("Calculator", "7"))
        self.pushButton_multiply.setText(_translate("Calculator", "x"))
        self.pushButton_5.setText(_translate("Calculator", "5"))
        self.pushButton_6.setText(_translate("Calculator", "6"))
        self.pushButton_4.setText(_translate("Calculator", "4"))
        self.pushButton_substract.setText(_translate("Calculator", "-"))
        self.pushButton_2.setText(_translate("Calculator", "2"))
        self.pushButton_3.setText(_translate("Calculator", "3"))
        self.pushButton_1.setText(_translate("Calculator", "1"))
        self.pushButton_add.setText(_translate("Calculator", "+"))
        self.pushButton_decimal.setText(_translate("Calculator", ","))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.pushButton_equals.setText(_translate("Calculator", "="))
